# Generated by Django 4.2.5 on 2023-09-19 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0002_plan_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'exercise',
                'verbose_name_plural': 'exercises',
            },
        ),
        migrations.AlterModelOptions(
            name='plan',
            options={'verbose_name': 'plan', 'verbose_name_plural': 'plans'},
        ),
        migrations.CreateModel(
            name='ExerciseVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('video_file', models.FileField(null=True, upload_to='videos/', verbose_name='')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plan.exercise')),
            ],
        ),
        migrations.AddField(
            model_name='exercise',
            name='plans',
            field=models.ManyToManyField(to='plan.plan'),
        ),
    ]
