# Generated by Django 4.2.5 on 2023-09-20 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0003_exercise_alter_plan_options_exercisevideo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercisevideo',
            name='exercise',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='plan.exercise'),
        ),
    ]
