# Generated by Django 4.2.5 on 2023-09-21 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'Gratis'), (2, 'Bronze'), (3, 'Prata'), (4, 'Ouro')], default=1, verbose_name='Subscription')),
            ],
        ),
    ]
