# Generated by Django 4.2.5 on 2023-09-21 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
        ('account', '0004_alter_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='physiotherapist',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='physiotherapist', to='subscription.subscription'),
        ),
    ]
