# Generated by Django 4.2.5 on 2023-09-06 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_user_types_physiotherapist_patient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='types',
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Paciente'), (2, 'Fisioterapeuta')], default=1, verbose_name='Role'),
        ),
    ]
